apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{ include "cert-manager-google-cas-issuer.labels" . | indent 4 }}
  name: {{ include "cert-manager-google-cas-issuer.name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cas-issuer.jetstack.io
  resources:
  - googlecasclusterissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cas-issuer.jetstack.io
  resources:
  - googlecasclusterissuers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cas-issuer.jetstack.io
  resources:
  - googlecasissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cas-issuer.jetstack.io
  resources:
  - googlecasissuers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  verbs:
  - get
  - patch
  - update
---
{{- if .Values.app.approval.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{ include "cert-manager-google-cas-issuer.labels" . | indent 4 }}
  name: {{ include "cert-manager-google-cas-issuer.name" . }}:approval
rules:
- apiGroups:
  - cert-manager.io
  resourceNames:
  - googlecasclusterissuers.cas-issuer.jetstack.io/*
  - googlecasissuers.cas-issuer.jetstack.io/*
  resources:
  - signers
  verbs:
  - approve
{{- end }}
