apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-manager-google-cas-issuer.name" . }}
  labels:
{{ include "cert-manager-google-cas-issuer.labels" . | indent 4 }}
  annotations:
{{ include "cert-manager-google-cas-issuer.serviceAccount.annotations" . | indent 4 }}
