# This workflow runs unprivileged unit tests.
name: unit-tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - id: go-version
      run: |
        make print-go-version >> "$GITHUB_OUTPUT"

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ steps.go-version.outputs.result }}

    - run: make test-unit
